apiRules:
- exclude:
    uidRegex: ^System
- exclude:
    uidRegex: ^UnityEngine
- exclude:
    uidRegex: ^UnityEditor
- exclude:
    uidRegex: ^Zigurous.Graphics.CheckerboardTextureDrawer.OnValidate
- exclude:
    uidRegex: ^Zigurous.Graphics.TextureDrawer.Awake
- exclude:
    uidRegex: ^Zigurous.Graphics.TextureDrawer.OnEnable
- exclude:
    uidRegex: ^Zigurous.Graphics.TextureDrawer.OnValidate
- exclude:
    uidRegex: ^Zigurous.Graphics.TextureDrawer.Update
